# Generated by Django 4.0.1 on 2022-01-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='name',
        ),
        migrations.AddField(
            model_name='producttype',
            name='product_type_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
