# Generated by Django 4.0.1 on 2022-02-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_alter_producttypes_product_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.profiles'),
        ),
    ]
